import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'
import { Pretendard } from './font'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko" className={Pretendard.variable}>
      <body className="bg-white text-zinc-700 antialiased dark:bg-zinc-900 dark:text-zinc-50">
        {children}
      </body>
    </html>
  )
}
